-- Land Registry V2 operational schema for Supabase PostgreSQL.
-- Apply through the Supabase SQL editor or a controlled migration runner.
CREATE EXTENSION IF NOT EXISTS postgis;
CREATE EXTENSION IF NOT EXISTS pgcrypto;

CREATE TABLE IF NOT EXISTS users (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(), identity_reference TEXT UNIQUE NOT NULL,
  aadhaar_hash TEXT UNIQUE, account_status TEXT NOT NULL DEFAULT 'ACTIVE', created_at TIMESTAMPTZ NOT NULL DEFAULT now(), updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE TABLE IF NOT EXISTS roles (code TEXT PRIMARY KEY CHECK (code IN ('OWNER','BUYER','NOMINEE','REGISTRAR','BANK','AUDITOR')));
INSERT INTO roles(code) VALUES ('OWNER'),('BUYER'),('NOMINEE'),('REGISTRAR'),('BANK'),('AUDITOR') ON CONFLICT DO NOTHING;
CREATE TABLE IF NOT EXISTS user_roles (user_id UUID NOT NULL REFERENCES users(id), role_code TEXT NOT NULL REFERENCES roles(code), PRIMARY KEY(user_id,role_code));
CREATE TABLE IF NOT EXISTS sessions (id UUID PRIMARY KEY DEFAULT gen_random_uuid(), user_id UUID NOT NULL REFERENCES users(id), token_hash TEXT UNIQUE NOT NULL, expires_at TIMESTAMPTZ NOT NULL, revoked_at TIMESTAMPTZ, created_at TIMESTAMPTZ NOT NULL DEFAULT now());
CREATE TABLE IF NOT EXISTS wallets (id UUID PRIMARY KEY DEFAULT gen_random_uuid(), user_id UUID NOT NULL REFERENCES users(id), wallet_address TEXT UNIQUE NOT NULL, created_at TIMESTAMPTZ NOT NULL DEFAULT now());
CREATE TABLE IF NOT EXISTS credentials (id UUID PRIMARY KEY DEFAULT gen_random_uuid(), user_id UUID NOT NULL REFERENCES users(id), wallet_id UUID NOT NULL REFERENCES wallets(id), status TEXT NOT NULL CHECK(status IN ('PROVISIONING','ACTIVE','DORMANT','SUSPENDED','RECOVERY_PENDING','REVOKED','EXPIRED','DECEASED')), supersedes_credential_id UUID REFERENCES credentials(id), activated_at TIMESTAMPTZ, revoked_at TIMESTAMPTZ, revoked_reason TEXT, created_at TIMESTAMPTZ NOT NULL DEFAULT now());
CREATE TABLE IF NOT EXISTS parcels (ulpin TEXT PRIMARY KEY, ownership_type TEXT NOT NULL, frozen BOOLEAN NOT NULL DEFAULT false, freeze_reason TEXT, centroid geometry(Point,4326), created_at TIMESTAMPTZ NOT NULL DEFAULT now(), updated_at TIMESTAMPTZ NOT NULL DEFAULT now());
CREATE TABLE IF NOT EXISTS parcel_geometries (parcel_id TEXT PRIMARY KEY REFERENCES parcels(ulpin), boundary geometry(Polygon,4326) NOT NULL, coordinate_system TEXT NOT NULL DEFAULT 'EPSG:4326', created_at TIMESTAMPTZ NOT NULL DEFAULT now());
CREATE TABLE IF NOT EXISTS ownerships (id UUID PRIMARY KEY DEFAULT gen_random_uuid(), parcel_id TEXT NOT NULL REFERENCES parcels(ulpin), user_id UUID NOT NULL REFERENCES users(id), credential_id UUID REFERENCES credentials(id), share_bps INT NOT NULL CHECK(share_bps BETWEEN 1 AND 10000), active BOOLEAN NOT NULL DEFAULT true, created_at TIMESTAMPTZ NOT NULL DEFAULT now(), UNIQUE(parcel_id,user_id,active));
CREATE TABLE IF NOT EXISTS nominees (id UUID PRIMARY KEY DEFAULT gen_random_uuid(), parcel_id TEXT NOT NULL REFERENCES parcels(ulpin), nominee_user_id UUID NOT NULL REFERENCES users(id), status TEXT NOT NULL DEFAULT 'DORMANT', created_at TIMESTAMPTZ NOT NULL DEFAULT now(), UNIQUE(parcel_id,nominee_user_id));
CREATE TABLE IF NOT EXISTS transfers (id TEXT PRIMARY KEY, parcel_id TEXT NOT NULL REFERENCES parcels(ulpin), buyer_user_id UUID REFERENCES users(id), status TEXT NOT NULL, document_hash TEXT NOT NULL, assessment_hash TEXT NOT NULL, required_approvals SMALLINT NOT NULL CHECK(required_approvals > 0), expires_at TIMESTAMPTZ NOT NULL, version INT NOT NULL DEFAULT 0, chain_tx_hash TEXT UNIQUE, created_at TIMESTAMPTZ NOT NULL DEFAULT now(), updated_at TIMESTAMPTZ NOT NULL DEFAULT now());
CREATE TABLE IF NOT EXISTS nonces (value UUID PRIMARY KEY, purpose TEXT NOT NULL, user_id UUID REFERENCES users(id), transfer_id TEXT REFERENCES transfers(id), expires_at TIMESTAMPTZ NOT NULL, consumed_at TIMESTAMPTZ, created_at TIMESTAMPTZ NOT NULL DEFAULT now());
CREATE TABLE IF NOT EXISTS transfer_approvals (transfer_id TEXT NOT NULL REFERENCES transfers(id), user_id UUID NOT NULL REFERENCES users(id), nonce UUID NOT NULL REFERENCES nonces(value), wallet_address TEXT NOT NULL, signature TEXT NOT NULL, typed_data_hash TEXT NOT NULL, approved_at TIMESTAMPTZ NOT NULL DEFAULT now(), PRIMARY KEY(transfer_id,user_id), UNIQUE(nonce));
CREATE TABLE IF NOT EXISTS documents (id UUID PRIMARY KEY DEFAULT gen_random_uuid(), sha256_hash TEXT UNIQUE NOT NULL, document_type TEXT NOT NULL, storage_reference TEXT NOT NULL, mime_type TEXT NOT NULL, size_bytes BIGINT NOT NULL CHECK(size_bytes > 0), uploaded_by UUID REFERENCES users(id), verification_status TEXT NOT NULL DEFAULT 'PENDING', created_at TIMESTAMPTZ NOT NULL DEFAULT now());
CREATE TABLE IF NOT EXISTS succession_cases (id TEXT PRIMARY KEY, parcel_id TEXT NOT NULL REFERENCES parcels(ulpin), nominee_user_id UUID REFERENCES users(id), status TEXT NOT NULL, evidence_document_id UUID REFERENCES documents(id), created_at TIMESTAMPTZ NOT NULL DEFAULT now(), updated_at TIMESTAMPTZ NOT NULL DEFAULT now());
CREATE TABLE IF NOT EXISTS encumbrances (id UUID PRIMARY KEY DEFAULT gen_random_uuid(), parcel_id TEXT NOT NULL REFERENCES parcels(ulpin), status TEXT NOT NULL, details JSONB NOT NULL DEFAULT '{}', created_at TIMESTAMPTZ NOT NULL DEFAULT now());
CREATE TABLE IF NOT EXISTS disputes (id UUID PRIMARY KEY DEFAULT gen_random_uuid(), parcel_id TEXT NOT NULL REFERENCES parcels(ulpin), status TEXT NOT NULL, details JSONB NOT NULL DEFAULT '{}', created_at TIMESTAMPTZ NOT NULL DEFAULT now());
CREATE TABLE IF NOT EXISTS notifications (id UUID PRIMARY KEY DEFAULT gen_random_uuid(), user_id UUID REFERENCES users(id), event_type TEXT NOT NULL, payload JSONB NOT NULL DEFAULT '{}', read_at TIMESTAMPTZ, created_at TIMESTAMPTZ NOT NULL DEFAULT now());
CREATE TABLE IF NOT EXISTS audit_events (id UUID PRIMARY KEY DEFAULT gen_random_uuid(), actor_user_id UUID REFERENCES users(id), actor_role TEXT, action TEXT NOT NULL, entity_type TEXT, entity_id TEXT, result TEXT NOT NULL, metadata JSONB NOT NULL DEFAULT '{}', created_at TIMESTAMPTZ NOT NULL DEFAULT now());
CREATE TABLE IF NOT EXISTS blockchain_outbox (id UUID PRIMARY KEY DEFAULT gen_random_uuid(), idempotency_key TEXT UNIQUE NOT NULL, aggregate_id TEXT NOT NULL, event_type TEXT NOT NULL, payload JSONB NOT NULL, status TEXT NOT NULL DEFAULT 'PENDING', attempts INT NOT NULL DEFAULT 0, tx_hash TEXT, last_error TEXT, created_at TIMESTAMPTZ NOT NULL DEFAULT now(), submitted_at TIMESTAMPTZ, confirmed_at TIMESTAMPTZ);
CREATE TABLE IF NOT EXISTS blockchain_events (id UUID PRIMARY KEY DEFAULT gen_random_uuid(), event_id TEXT UNIQUE NOT NULL, tx_hash TEXT NOT NULL, block_number BIGINT NOT NULL, event_name TEXT NOT NULL, parcel_id TEXT, transfer_id TEXT, event_timestamp TIMESTAMPTZ, raw_event JSONB NOT NULL, indexed_at TIMESTAMPTZ NOT NULL DEFAULT now());
CREATE INDEX IF NOT EXISTS parcel_geometries_gix ON parcel_geometries USING GIST(boundary);
CREATE INDEX IF NOT EXISTS transfers_status_idx ON transfers(status, created_at);
CREATE INDEX IF NOT EXISTS outbox_status_idx ON blockchain_outbox(status, created_at);
CREATE INDEX IF NOT EXISTS audit_entity_idx ON audit_events(entity_type, entity_id, created_at DESC);
